<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daniel Yan, Ziqian Zhao, Nazhah Mir, Xiaofeng Cai">
<meta name="dcterms.date" content="2024-10-30">

<title>Biomarkers of ASD</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="report_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="report_files/libs/d3-3.3.8/d3.min.js"></script>
<script src="report_files/libs/dagre-0.4.0/dagre-d3.min.js"></script>
<link href="report_files/libs/mermaid-0.3.0/dist/mermaid.css" rel="stylesheet">
<script src="report_files/libs/mermaid-0.3.0/dist/mermaid.slim.min.js"></script>
<link href="report_files/libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
<script src="report_files/libs/chromatography-0.1/chromatography.js"></script>
<script src="report_files/libs/DiagrammeR-binding-1.0.11/DiagrammeR.js"></script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biomarkers of ASD</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Daniel Yan, Ziqian Zhao, Nazhah Mir, Xiaofeng Cai </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Updated</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 30, 2024</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="cell" data-hash="report_cache/html/unnamed-chunk-1_ed00b55140779c96e5726f4fc7cf7b85">

</div>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This study uses data from Hewitson et al.&nbsp;(2021), which includes 154 male pediatric subjects classified into ASD (autism spectrum disorder) and TD (typically developing) groups. Following log transformation and trimmed outliers, we split the dataset into training and testing sets. Instead of using random forest, t-tests, and logistic regression to select proteins like the original article, we explored three different methodologies to see which models would fare better than the original. We first split the dataset into a training and testing dataset and applied the three tests only on the training data to identify the proteins and fitted them into a logistic regression model. This model improved in sensitivity, specificity, and accuracy, but had a worse ROC AUC score. Our next method was altering the number of potential proteins from top 10 to top 20 and following the same steps as the in-class model. The model that has 20 predictive proteins returned a better ROC AUC (area under the curve) value and improved accuracy and specificity, but poorer sensitivity. In addition, we explored a fuzzy intersection, which took proteins that were identified by one of the testing methods instead of both and used those as predictors in the model. This model had significantly poorer performance than the original, with it only improving the specificity value.s Lastly, we tried a 15-protein panel and achieved improved classification accuracy.</p>
</section>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">Dataset</h2>
<p>The data provided in Hewitson et al.&nbsp;(2021) were initially collected in 2017 consists of 154 male pediatric subjects (mostly White/Caucasian and Hispanic/Latino, over 80% of the sample size). All participants were classified into two groups: ASD (autism spectrum disorder) and TD (typically developing). The ASD group was comprised of 76 subjects with a mean age of 5.6 years (SD 1.7 years); The TD group was comprised of 78 subjects with a mean age of 5.7 years (SD 2.0 years). 1317 protein were measured for each sample, 192 of them were failed in the quality control, so 1125 proteins were analyzed. In addition to quality control, the data was normalized by taking log transformation and trimming out the outlier by z-transformation.</p>
</section>
<section id="summary-of-published-analysis" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-published-analysis">Summary of published analysis</h2>
<p>To find the protein for ASD prediction, the paper uses three different methods: random forest(RF), t-test, and correlation-based methods.</p>
<p>Specifically, they use three methods to select the top ten predictive protein from each method, find their intersection : <code>DERM</code>, <code>suPAR</code>, <code>MAPK14</code>, <code>EPHB2</code>, and <code>IgD</code></p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-2_4b53ab915b5c7b81993d936a2a377992">
<div class="cell-output-display">
<div class="DiagrammeR html-widget html-fill-item" id="htmlwidget-a6b9949fb19da064228d" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-a6b9949fb19da064228d">{"x":{"diagram":"\ngraph LR\n  A[Data Collected] --> B(Preprocessing)\n  B --> C(Random Forest)\n  B --> D(t-test)\n  B --> E(correlation-based method)\n  C --> F{5 core protein} \n  D --> F{5 core protein}\n  E --> F{5 core protein}        \n  "},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>Taking those as the core proteins, a predictive model is trained with them. They further investigate the 13 proteins left in whether they provided additive predictive power. Along with these models, a logistic regression model is implemented to investigate the accuracy. It was discovered that four additional proteins provided additive predictive power, so a total of 9 proteins resulted in an AUC of 86% with a sensitivity of 83% and specificity of 84%.</p>
</section>
<section id="findings" class="level2">
<h2 class="anchored" data-anchor-id="findings">Findings</h2>
<section id="impact-of-preprocessing-and-outliers" class="level3">
<h3 class="anchored" data-anchor-id="impact-of-preprocessing-and-outliers">Impact of preprocessing and outliers</h3>
<section id="task-1" class="level4">
<h4 class="anchored" data-anchor-id="task-1">Task 1</h4>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-3_9a18b11a75d338f93eb01118aadd86bf">

</div>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-4_4e61cbba387a87938500396962ad4923">
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-5_51e49e9680fa90f31094b0f971fd8cba">
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We compare the data before processing and after processing. Specifically, we compare the raw data set and data after log-transformation and scaling. We randomly selected two sample protein types and examine the normality. It could be seen that <code>DERM</code> is normally distributed before pre-processing but not centered at 0, while <code>Mcl-1</code> is neither normally distributed nor centralized. Therefore, we could conclude that not all protein types are normally distributed in the raw data, so a log-transformation is used. By using this method, the data used for further model training could be more reliable.</p>
</section>
<section id="task-2" class="level4">
<h4 class="anchored" data-anchor-id="task-2">Task 2</h4>
<p>To do some exploratory analysis of outlying values. First, we counted the number of outliers (Z-scores &gt; 3) standard deviation from the mean) per subject.</p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-6_8e0bd747ab7cc041e3e82515ebf2a61f">

</div>
<p>Most subjects have 0 to 3 outliers, but we are more interested in subjects with more than 4 outliers.</p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-7_8492b8905c7bfc5d6378fa06f6c595f7">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 34 × 3
   group Column                    Outlier_Count
   &lt;chr&gt; &lt;chr&gt;                             &lt;int&gt;
 1 ASD   SIG14                                 5
 2 ASD   Ephrin-A3                             4
 3 ASD   Annexin V                             4
 4 ASD   C1q                                   4
 5 ASD   IL-17F                                4
 6 ASD   CDK5/p35                              4
 7 ASD   TLR2                                  4
 8 ASD   Phosphoglycerate mutase 1             4
 9 ASD   NUDC3                                 4
10 ASD   TGM3                                  4
# ℹ 24 more rows</code></pre>
</div>
</div>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-8_def1ffce099fac8c3fe2130fed3e0968">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  group     n
  &lt;chr&gt; &lt;int&gt;
1 ASD      16
2 TD       18</code></pre>
</div>
</div>
<p>We found that the ASD group has 16 subjects with outliers greater than 4, with a maximum of 5 outliers per subject. The TD group has 18 subjects with outliers greater than 4, with a maximum of 4 outliers per subject.</p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-9_6aca8ce85ea0ba0a31cc2e9e07b7efed">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
# Rowwise: 
  group Total_Outliers
  &lt;chr&gt;          &lt;int&gt;
1 ASD             1016
2 TD              1312</code></pre>
</div>
</div>
<p>We also calculated the total number of outliers within each group and found that there are more outliers in the TD group than in the ASD group.</p>
</section>
</section>
<section id="methodological-variations" class="level3">
<h3 class="anchored" data-anchor-id="methodological-variations">Methodological variations</h3>
<p><strong>Original Methodology (from <em>inclass-analysis.R</em>):</strong></p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-10_f9bb09fd5d644183ec23ce2cbcd7ec14">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 sensitivity binary         0.812
2 specificity binary         0.733
3 accuracy    binary         0.774
4 roc_auc     binary         0.883</code></pre>
</div>
</div>
<p><strong>Task 3</strong> <strong>(Data split before variable selection)</strong></p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-11_7cfb619bc2c8840adb3278625b5fb4b6">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 sensitivity binary         0.875
2 specificity binary         0.75 
3 accuracy    binary         0.812
4 roc_auc     binary         0.820</code></pre>
</div>
</div>
<p>Comparing the split model to the original in class analysis, we can see that sensitivity of the model increased from 0.812 to 0.875, meaning that the model became better at detecting true positives, or ASD cases. The specificity of the model also increased slightly from 0.733 to 0.75, meaning that the model also became slightly better at identifying true negatives, or TD cases. The accuracy of the model also improved from 0.774 to 0.812, which suggests that splitting the model into training and testing data does in fact perform better in predicting both classes correctly. However, the ROC AUC score dropped from 0.883 to 0.820, which indicates that the model’s ability to distinguish between positive and negative thresholds has decreased. The high ROC AUC score from the initial model can be attributed to overfitting, as the model could have recognized patterns specific to the test set because the same data was used to train and test. This means that the model where the data was trained on a separate set of data is better, as it trades off class separation capability for improved generalization.</p>
<p><strong>Task 3 (larger panel of proteins)</strong></p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-12_02a441cb132d52f9c5e2853350439228">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 sensitivity binary         0.75 
2 specificity binary         0.867
3 accuracy    binary         0.806
4 roc_auc     binary         0.892</code></pre>
</div>
</div>
<p>The model with 20 proteins performs a lot differently than the original model with 10 proteins from the in class analysis. First, the sensitivity decreased from 0.812 to 0.75, which means the new model’s ability to correctly identify cases of ASD has decreased. However, the specificity increased from 0.733 to 0.867, which means that the model performs better in identifying non-ASD cases. The model’s accuracy also improved from 0.774 to 0.806, which means that the new model correctly classifies more cases in total. Lastly, the ROC AUC score also improved slightly, from 0.883 to 0.892, which means that the model is able to separate positive and negative cases better. By adding 20 proteins instead of 10, the model can better identify negative cases and distinguish between negative and positive cases better. However, the addition of these new features diluted the predictors for positive ASD cases, decreasing the sensitivity.</p>
<p><strong>Task 3 (Fuzzy Intersection)</strong></p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-13_5119f79ad7709119c29077cb865446b2">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 sensitivity binary         0.562
2 specificity binary         0.8  
3 accuracy    binary         0.677
4 roc_auc     binary         0.783</code></pre>
</div>
</div>
<p>For the model using fuzzy intersection, we decided to create a fuzzy score threshold that the protein had to meet in order to be included in the model. The score represents how many panels the protein is included in. In the original model, the protein had to be included in both the random forest panel and the multiple testing panel to be included, but for the model using fuzzy intersection, the protein only has to be included in one of the panels to be included in the model, which is represented by a fuzzy score threshold of 1. This model performed significantly worse than the original in-class model. The sensitivity decreased from 0.812 to 0.562, which is a significant decrease in the model’s ability to classify true positives, or ASD cases, correctly. On the other hand, the specificity increased from 0.733 to 0.80, which means that this model is better at classifying true negatives, or TD cases, better than the original model. However, the model’s accuracy from 0.774 to 0.677, meaning that it classified less cases correctly than the original model. Lastly, the ROC AUC score of the fuzzy intersection model decreased as well, from 0.883 to 0.783, showing that the new model’s overall ability to distinguish between positive or negative cases decreased. It makes sense that the fuzzy intersection model performs more poorly than the original model. Fuzzy intersection allows proteins that are only selected by one of the methods to be included in the final model, which might include predictors that are not as relevant or add features that do not correlate with the target variable, in this case ASD or TD cases.</p>
</section>
<section id="improved-classifier" class="level3">
<h3 class="anchored" data-anchor-id="improved-classifier">Improved classifier</h3>
<p><strong>Task 4 (Improved panel of proteins)</strong></p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-14_d1caa3ca1f2ca5961997473ae3722edb">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 sensitivity binary         0.938
2 specificity binary         0.8  
3 accuracy    binary         0.871
4 roc_auc     binary         0.896</code></pre>
</div>
</div>
<p>Instead of choosing 20 predictive proteins in each method, we choose to select top 15 predictive proteins in each method, taking the hard intersection, then explore the accuracy. Comparing between <code>improved panel model</code> and previous ones (<code>larger panel model</code> and <code>fuzzy intersection model</code>), it could be seen that the sensitivity has improved to 0.938. This means that the model could better detect the positive cases. Specifically, 93.8% children were correctly identified with ASD. Additionally, the specificity increased from 0.733 to 0.8, indicating that the improved the model is more effective in detecting the TD group children than the previous model. The accuracy of the <code>improved model</code> had increased to 0.871, meaning that the model of correctly identified the children 87.1% of time.</p>
<p>Overall, the model is improved with an alternative panel. Specifically, we reduced the protein selections from 20 predictive proteins to 15 predictive proteins. The latter model has been improved its ability in detecting ASD group while the ability in detecting the TD has not been compromised.</p>
<p>The reducing in selecting protein could potentially exclude less informative protein and exclude nosier protein, which produce a better prediction. Moreover, intersection of 15 proteins is more refined, where the protein could possibly stronger correlated to target (ASD/TD group). Furthermore, a smaller protein panel could prevent the model from overfitting, which may generalized better in test data.</p>
<p>However, it could be seen that, though accuracy has increased, the AUC has not increased much, which indicate that the overall discriminative power does not improve a lot. Therefore, further optimization strategies could apply to further improve the model in order to improve this.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>